# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bad1c99a499a1dd598a83881ae39f5f8c12ca4d1bde467026b1b5f0219d58828a4a577386705fb5990bdd1de203c94a640f529adc5b777392be48c3c28cb5eb1

test:
  secret_key_base: 2ead137955aa9d5f9b90ba2bc1de6e5271a443b9d12339a62326ef4358e00a3ecf887941483f0c17e8a8d1f8dc0be0a78ce10838b3b3a427ec9e097765ef30e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
